print('Введите текст.')
print('')
text = input()
print('')
symbol = input('Введите символ, который нужно удвоить в введёном тексте>>> ')
text = text.replace(symbol, symbol * 2)
print('')
print('Ниже выведен текст с удвоенным символом.')
print('')
print(text)
